name: logdevice

on:
  push:
    tags:
      - '*'
    branches:
      - release

  pull_request:

env:
  IMAGE_NAME: ghcr.io/commelina/jepsen_logdevice

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build & push images
        run: |
          image_tag=0.1.0
          docker build ./ld -f ld/Dockerfile -t $IMAGE_NAME:${image_tag}
          echo "Try pushing: $IMAGE_NAME:${image_tag}..."
          if [ "${{ github.event_name }}" == 'push' ]; then
            docker push $IMAGE_NAME:${image_tag}
          else
            echo "Ignoring."
          fi
